"use client";

import { useState } from 'react';

interface ReportData {
  fileId: string;
  filename: string;
  uploadDate: string;
  fileSize: string;
  analysisResults?: {
    riskScore: number;
    detectedIssues: string[];
    confidence: number;
    recommendations: string[];
  };
}

interface PDFGeneratorProps {
  reportData: ReportData;
  onError?: (error: string) => void;
}

const PDFGenerator: React.FC<PDFGeneratorProps> = ({ reportData, onError }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);
    
    try {
      // Dynamic import to avoid SSR issues
      const { jsPDF } = await import('jspdf');
      
      // Create new PDF document
      const doc = new jsPDF();
      
      // PDF Configuration
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const lineHeight = 7;
      let yPosition = margin;

      // Helper function to add text with word wrap
      const addText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 12) => {
        doc.setFontSize(fontSize);
        const textLines = doc.splitTextToSize(text, maxWidth);
        doc.text(textLines, x, y);
        return y + (textLines.length * lineHeight);
      };

      // Header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('CheckGuard AI - Analysis Report', margin, yPosition);
      yPosition += 15;

      // Add a horizontal line
      doc.setLineWidth(0.5);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // File Information Section
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('File Information', margin, yPosition);
      yPosition += 10;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      yPosition = addText(`File ID: ${reportData.fileId}`, margin, yPosition, pageWidth - 2 * margin);
      yPosition = addText(`Filename: ${reportData.filename}`, margin, yPosition, pageWidth - 2 * margin);
      yPosition = addText(`Upload Date: ${reportData.uploadDate}`, margin, yPosition, pageWidth - 2 * margin);
      yPosition = addText(`File Size: ${reportData.fileSize}`, margin, yPosition, pageWidth - 2 * margin);
      yPosition += 10;

      // Analysis Results Section (if available)
      if (reportData.analysisResults) {
        const { riskScore, detectedIssues, confidence, recommendations } = reportData.analysisResults;

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Analysis Results', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        
        // Risk Score
        yPosition = addText(`Risk Score: ${riskScore}/100`, margin, yPosition, pageWidth - 2 * margin);
        yPosition = addText(`Confidence Level: ${confidence}%`, margin, yPosition, pageWidth - 2 * margin);
        yPosition += 5;

        // Detected Issues
        if (detectedIssues.length > 0) {
          doc.setFont('helvetica', 'bold');
          yPosition = addText('Detected Issues:', margin, yPosition, pageWidth - 2 * margin);
          doc.setFont('helvetica', 'normal');
          
          detectedIssues.forEach((issue, index) => {
            yPosition = addText(`${index + 1}. ${issue}`, margin + 10, yPosition, pageWidth - 2 * margin - 10);
          });
          yPosition += 5;
        }

        // Recommendations
        if (recommendations.length > 0) {
          doc.setFont('helvetica', 'bold');
          yPosition = addText('Recommendations:', margin, yPosition, pageWidth - 2 * margin);
          doc.setFont('helvetica', 'normal');
          
          recommendations.forEach((recommendation, index) => {
            yPosition = addText(`${index + 1}. ${recommendation}`, margin + 10, yPosition, pageWidth - 2 * margin - 10);
          });
          yPosition += 5;
        }
      } else {
        // No analysis results yet
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Analysis Status', margin, yPosition);
        yPosition += 10;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        yPosition = addText('Analysis is pending. This report contains file upload information only.', margin, yPosition, pageWidth - 2 * margin);
        yPosition += 10;
      }

      // Footer
      yPosition = pageHeight - 30;
      doc.setLineWidth(0.5);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('Generated by CheckGuard AI', margin, yPosition);
      doc.text(new Date().toLocaleString(), pageWidth - margin - 60, yPosition);
      yPosition += 5;
      doc.text('© 2024 CheckGuard AI. All rights reserved.', margin, yPosition);

      // Save the PDF
      const fileName = `checkguard-report-${reportData.fileId}.pdf`;
      doc.save(fileName);

    } catch (error) {
      console.error('Error generating PDF:', error);
      onError?.('Failed to generate PDF report. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex flex-col items-center space-y-4">
      <div className="bg-white p-6 rounded-lg shadow-sm border">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Generate PDF Report</h3>
        
        <div className="mb-4">
          <p className="text-sm text-gray-600">
            Generate a comprehensive PDF report containing file information and analysis results.
          </p>
        </div>

        <div className="flex items-center justify-between">
          <div className="text-sm text-gray-500">
            Report for: {reportData.filename}
          </div>
          <button
            onClick={generatePDF}
            disabled={isGenerating}
            className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Generating...
              </>
            ) : (
              <>
                <svg className="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Generate PDF
              </>
            )}
          </button>
        </div>
      </div>

      <div className="text-xs text-gray-500 text-center max-w-md">
        PDF reports include file information, analysis results, and recommendations. 
        The generated PDF will be automatically downloaded to your device.
      </div>
    </div>
  );
};

export default PDFGenerator;